"""Generate docs/src/architecture/component_registry.rst from REGISTRY.

The registry is data, so keep it here and regenerate the page:

    python3 docs/tools/component_registry.py

Each entry must fill every field in FIELDS. Use "—" when a field does not
apply. Confidence is CONFIRMED, INFERRED or UNVERIFIED (see docs/src/index.rst).
"""

from __future__ import annotations

from pathlib import Path

FIELDS = [
    ("path", "Repository path"),
    ("feature", "Product feature"),
    ("language", "Language"),
    ("runtime", "Runtime"),
    ("build", "Build system"),
    ("ownership", "Ownership"),
    ("upstream", "Upstream project"),
    ("entrypoint", "Entrypoint"),
    ("inputs", "Inputs"),
    ("outputs", "Outputs"),
    ("consumers", "Consumers"),
    ("persistence", "Persistence"),
    ("network", "Network dependency"),
    ("credentials", "Credentials"),
    ("verification", "Verification"),
    ("origin", "Historical origin"),
    ("confidence", "Confidence"),
]

REGISTRY: list[dict[str, str]] = [
    {
        "name": "Whiteboard CLI",
        "path": "``packages/review/src/cli.ts``, ``cli-runner.ts``",
        "feature": "Launch Desktop, headless authoring, traces, sharing, instance selection",
        "language": "TypeScript",
        "runtime": "Node 24, or Electron-as-Node when delegated to Desktop's bundled CLI",
        "build": "pnpm + tsdown (``dist/cli.js``)",
        "ownership": "Whiteboard-owned",
        "upstream": "—",
        "entrypoint": "bins ``whiteboard`` and ``review`` → ``dist/cli.js``",
        "inputs": "argv, environment (``DEV_REVIEW_*``), discovery records",
        "outputs": "Human text, or NDJSON events with ``--json``; HTTP calls to a server",
        "consumers": "Users, agent skills (Pi), Git hooks, agent harness hooks",
        "persistence": "Reads ``$DEV_REVIEW_HOME``; writes ``default-instance`` and trace config",
        "network": "Loopback HTTP to the server; GitHub for ``login`` and ``share``",
        "credentials": "Server token (read from discovery); GitHub login for share and hosted traces",
        "verification": "``pnpm review version``, ``--help`` and ``cli.test.ts`` (run)",
        "origin": "Pre-import (``d1c6463c``); renamed with the package in #259",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Embedded Desktop server",
        "path": "``packages/review/src/server/desktop-host.ts``, ``desktop-server.ts``",
        "feature": "The single per-instance backend for Desktop, CLI and MCP",
        "language": "TypeScript",
        "runtime": "Node inside an Electron ``UtilityProcess``",
        "build": "pnpm + tsdown (``dist/server/desktop-host.js``)",
        "ownership": "Whiteboard-owned",
        "upstream": "—",
        "entrypoint": "``runDesktopHost()``, started by ``reviewServerSupervisor.ts``",
        "inputs": "``DEV_FAST_REVIEW_SERVER_*`` environment from Electron main; HTTP requests",
        "outputs": "A ``ready`` JSON line on stdout; HTTP/NDJSON/SSE responses; a discovery record",
        "consumers": "Desktop renderer, canvas, CLI, MCP adapter",
        "persistence": "``review-api.db`` (SQLite), ``review-desktop/instances/<key>.json``",
        "network": "Loopback listener; PostHog; spawns diffr; GitHub for PR reviews",
        "credentials": "Random 32-byte token from Electron main (``x-review-token``)",
        "verification": "``desktop-server-*.test.ts`` (run); live launch NOT verified",
        "origin": "Pre-import; the JSON API arrived in #264",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Headless server",
        "path": "``packages/review/src/server/headless-host.ts``",
        "feature": "Authoring without Desktop (CI, GitHub Actions)",
        "language": "TypeScript",
        "runtime": "Node 24 (foreground process)",
        "build": "pnpm + tsdown (part of ``dist/cli.js``)",
        "ownership": "Whiteboard-owned",
        "upstream": "—",
        "entrypoint": "``whiteboard server start`` → ``runHeadlessServer()``",
        "inputs": "``--state-dir``, ``--port``; HTTP requests",
        "outputs": "HTTP API; a ``review-server`` discovery file",
        "consumers": "``whiteboard api``, ``whiteboard mcp`` with ``--state-dir``",
        "persistence": "``<state-dir>/review-api.db``, ``headless-server.lock``",
        "network": "Loopback only (sharing publish optional)",
        "credentials": "Generated token in the discovery file",
        "verification": "Started, then drove create, edit, get and diff through ``api`` and MCP (run)",
        "origin": "#356 (2026-09-21)",
        "confidence": "CONFIRMED",
    },
    {
        "name": "JSON review store and HTTP API",
        "path": "``packages/review/src/review-api/``",
        "feature": "Versioned, validated review documents pinned to commits",
        "language": "TypeScript",
        "runtime": "Node (inside either server)",
        "build": "pnpm + tsdown (bundled)",
        "ownership": "Whiteboard-owned",
        "upstream": "—",
        "entrypoint": "``createReviewApi()`` in ``http.ts``, mounted at ``/reviews-api``",
        "inputs": "Commands (``POST /commands``), reads, uploads, activity leases",
        "outputs": "JSON snapshots, NDJSON watch streams, structural-diff NDJSON",
        "consumers": "Canvas, Desktop services, MCP and ``api`` adapters",
        "persistence": "SQLite tables: reviews, versions, receipts, repositories, resources, attention, authoring_sessions",
        "network": "None beyond loopback; PR resolution uses ``gh`` or the GitHub API",
        "credentials": "Server token; ``gh`` credentials for private PRs",
        "verification": "``review-api.test.ts`` and others (1185 tests run)",
        "origin": "#264–#270 (JSON Review 1/5–5/5)",
        "confidence": "CONFIRMED",
    },
    {
        "name": "MCP adapter",
        "path": "``packages/review/src/review-api/mcp.ts``",
        "feature": "Agent tool access",
        "language": "TypeScript",
        "runtime": "Node, a stdio child process of the agent",
        "build": "pnpm + tsdown",
        "ownership": "Whiteboard-owned (uses the external ``@modelcontextprotocol/sdk``)",
        "upstream": "MCP SDK 1.30.0",
        "entrypoint": "``whiteboard mcp``",
        "inputs": "JSON-RPC over stdin (``initialize``, ``tools/list``, ``tools/call``)",
        "outputs": "JSON-RPC over stdout; text content, with ``isError`` on failure",
        "consumers": "Claude Code, Codex, Cursor, OpenCode",
        "persistence": "None (stateless per request)",
        "network": "Loopback HTTP to the selected server",
        "credentials": "Server token from the discovery record",
        "verification": "Stdio smoke test: initialize, 28 tools, calls, error shape (run)",
        "origin": "#268; ``session_*`` names from #506",
        "confidence": "CONFIRMED",
    },
    {
        "name": "``api`` adapter",
        "path": "``packages/review/src/review-api/agent-cli.ts``",
        "feature": "Shell-based tool access (Pi skill, scripts, CI)",
        "language": "TypeScript",
        "runtime": "Node, one-shot",
        "build": "pnpm + tsdown",
        "ownership": "Whiteboard-owned",
        "upstream": "—",
        "entrypoint": "``whiteboard api <tool> '<json>'``",
        "inputs": "Tool name plus a JSON argument (or ``-`` for stdin)",
        "outputs": "Tool result on stdout",
        "consumers": "Pi skill, GitHub Actions, humans",
        "persistence": "None",
        "network": "Loopback HTTP",
        "credentials": "Server token from discovery",
        "verification": "``api tools``, ``session_*`` calls (run)",
        "origin": "#268",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Canvas",
        "path": "``packages/review/app`` (``@dev.fast/review-canvas``)",
        "feature": "Rendering documents, diagrams, traces, diffs; live drawing",
        "language": "TypeScript/TSX (React 19)",
        "runtime": "Chromium renderer inside the Desktop workbench (a dynamically imported ES module)",
        "build": "pnpm + Vite 8 (``desktop.vite.config.ts``)",
        "ownership": "Whiteboard-owned",
        "upstream": "Uses React, @xyflow/react, elkjs (EPL-2.0), libavoid-js (LGPL)",
        "entrypoint": "``mountReviewCanvas()`` from the Vite bundle",
        "inputs": "Server URL and token; JSON snapshots; NDJSON watch lines",
        "outputs": "DOM; Copy for Agent clipboard text; UI telemetry through the host",
        "consumers": "``reviewCanvasPart.ts`` in the fork",
        "persistence": "None of its own (per-viewer UI state only)",
        "network": "Loopback HTTP to the server",
        "credentials": "Server token passed through the bridge",
        "verification": "93 files and 517 tests, including Browser Mode (run with a Chromium shim)",
        "origin": "Pre-import as ``progressive-review/app``; split from the Node runtime in #366",
        "confidence": "CONFIRMED",
    },
    {
        "name": "libavoid WASM edge router",
        "path": "``node_modules/@mr_mint/elkjs-libavoid/dist/libavoid.wasm`` (copied by ``copy-canvas.mjs``)",
        "feature": "Orthogonal edge routing in software maps and database lenses",
        "language": "C++ compiled to WebAssembly",
        "runtime": "WASM in the canvas's Chromium renderer",
        "build": "Prebuilt npm artifact (not built here)",
        "ownership": "External (LGPL-2.1-or-later)",
        "upstream": "``Aksem/libavoid-js``",
        "entrypoint": "``wasmUrl`` passed to the canvas session",
        "inputs": "Graph geometry from ELK",
        "outputs": "Routed edge paths",
        "consumers": "Software map and database lens views",
        "persistence": "—",
        "network": "None",
        "credentials": "—",
        "verification": "``database-lens.test.tsx`` loads it (run)",
        "origin": "Pre-import (documented in ``THIRD_PARTY_NOTICES.md``)",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Whiteboard workbench (fork-owned code)",
        "path": "``apps/review-desktop/code-oss/src/vs/review/`` (149 files)",
        "feature": "Home, review tabs, canvas host, diff views, install, update, telemetry",
        "language": "TypeScript",
        "runtime": "Electron main, renderer and utility processes",
        "build": "Code - OSS gulp/esbuild (``build.sh``)",
        "ownership": "Whiteboard-owned inside a vendored tree",
        "upstream": "Uses VS Code platform APIs",
        "entrypoint": "``review.desktop.main.ts``; ``electron-main/*`` contributions",
        "inputs": "The server connection over IPC (``getConnection``), NDJSON streams",
        "outputs": "Workbench UI; starts the server process",
        "consumers": "End users",
        "persistence": "Code - OSS profile under ``review-desktop/state``",
        "network": "Loopback; update feed",
        "credentials": "Generates the server token",
        "verification": "``pnpm --filter @dev.fast/review-desktop test`` (197 tests run); build NOT verified",
        "origin": "Pre-import",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Vendored Code - OSS",
        "path": "``apps/review-desktop/code-oss/`` (6,406 tracked files)",
        "feature": "Editor, LSP hosting, multi-diff, extension host, Electron app shell",
        "language": "TypeScript (+ upstream Rust ``cli/`` and ``build/win32``, both unbuilt here)",
        "runtime": "Electron 42.10.0",
        "build": "npm (never pnpm) + gulp/esbuild; ``tsgo`` typecheck",
        "ownership": "Vendored upstream, with enumerated divergences",
        "upstream": "``microsoft/vscode`` at ``8a7abeba`` (code-oss-dev 1.129.1)",
        "entrypoint": "``src/main.ts`` → ``vs/code/electron-main/app.ts``",
        "inputs": "—",
        "outputs": "The Desktop application",
        "consumers": "The Whiteboard workbench",
        "persistence": "User-data profile",
        "network": "Build time: npm, Electron headers, GitHub; runtime: update feed",
        "credentials": "Apple signing and notarization for releases",
        "verification": "Dependency install and build FAILED here (network)",
        "origin": "``d1c6463c`` import",
        "confidence": "CONFIRMED",
    },
    {
        "name": "diffr semantic-diff engine",
        "path": "Not in the repository. Fetched to ``packages/review/bin/diffr``",
        "feature": "Semantic/structural diff, folding, hiding, summaries",
        "language": "Rust (derived from difftastic; tree-sitter 0.26, git2, wasmtime 34)",
        "runtime": "Native executable (macOS arm64, Linux x64 only)",
        "build": "Cargo in ``devdotfast/diffr`` (external); fetched by ``diffr-fetch``",
        "ownership": "External (dev.fast-owned, separate repository)",
        "upstream": "``devdotfast/diffr``; difftastic (strings in the binary)",
        "entrypoint": "``diffr --repo … --format ndjson --stream-annotations <base> <head> -- [paths]``",
        "inputs": "Repository path and revisions (reads Git objects itself)",
        "outputs": "NDJSON wire version 4: ``start``, ``file``, ``annotations``, ``complete``",
        "consumers": "``server/structural-diff.ts``, ``diffr-config.ts``",
        "persistence": "User diffr config (``diffr config``)",
        "network": "Only the optional summarize plugin (Gemini)",
        "credentials": "``GEMINI_API_KEY`` / ``GOOGLE_API_KEY`` or a saved key, for summaries",
        "verification": "Fetched, run on a real commit, failure probes, ``test:integration:diffr`` 9/9 (run)",
        "origin": "Integrated in ``9af69be2``/#245; bundled in #394",
        "confidence": "CONFIRMED (binary behavior); UNVERIFIED (Rust source internals)",
    },
    {
        "name": "``@dev.fast/diffr`` contract package",
        "path": "npm dependency (``node_modules/@dev.fast/diffr``)",
        "feature": "TypeScript mirror of diffr's wire format plus a binary fetcher",
        "language": "TypeScript + Node ESM script",
        "runtime": "Node (fetcher); anywhere zod runs (schemas)",
        "build": "External (built with tsc and bun in ``devdotfast/diffr``)",
        "ownership": "External (dev.fast)",
        "upstream": "``devdotfast/diffr`` ``diffr-ts/``",
        "entrypoint": "``decodeStructuralDiffEvent()``; bin ``diffr-fetch``",
        "inputs": "NDJSON lines; ``pins.json`` sha256 hashes",
        "outputs": "Validated ``StructuralDiffEvent``; a verified binary in ``bin/``",
        "consumers": "``review-protocol`` (re-export), ``packages/review``",
        "persistence": "``bin/diffr.stamp.json``",
        "network": "GitHub releases (fetch only)",
        "credentials": "—",
        "verification": "Contract decode during the diffr run (run)",
        "origin": "Pinned at exactly 0.1.3 (#535)",
        "confidence": "CONFIRMED",
    },
    {
        "name": "review-protocol",
        "path": "``packages/review-protocol``",
        "feature": "Shared contracts: discovery, CLI install, bug report, code peeks, structural diff",
        "language": "TypeScript (zod 4)",
        "runtime": "Node, browser, and generated into the fork",
        "build": "tsc; ``scripts/generate-native-source.mjs`` for the fork",
        "ownership": "Whiteboard-owned (private)",
        "upstream": "Re-exports ``@dev.fast/diffr``",
        "entrypoint": "``src/index.ts``",
        "inputs": "—",
        "outputs": "Schemas and types; ``code-oss/src/vs/review/common/reviewProtocol.ts`` (generated, gitignored)",
        "consumers": "Server, canvas, fork, CLI",
        "persistence": "—",
        "network": "—",
        "credentials": "—",
        "verification": "76 tests (run)",
        "origin": "Pre-import; ``json`` split out in #256; overlay generated at build since #98",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Sharing + review-share-protocol",
        "path": "``packages/review/src/sharing``, ``packages/review-share-protocol``",
        "feature": "Immutable review snapshots shared between machines",
        "language": "TypeScript",
        "runtime": "Node",
        "build": "tsc (protocol, published 0.1.1); bundled (sharing)",
        "ownership": "Whiteboard-owned",
        "upstream": "—",
        "entrypoint": "``whiteboard share`` / ``share revoke``",
        "inputs": "A review version and its pinned GitHub checkout",
        "outputs": "Share link; imported shared review",
        "consumers": "Desktop ``contrib/sharing``, CLI",
        "persistence": "Local store; remote share host",
        "network": "Yes: the hosted store ``https://app.dev.fast`` (``DEFAULT_STORE_ORIGIN``; overridable with ``DEV_REVIEW_SHARE_ORIGIN``)",
        "credentials": "GitHub login",
        "verification": "``sharing/*.test.ts`` (run); remote service NOT verified",
        "origin": "#338",
        "confidence": "CONFIRMED (client); UNVERIFIED (service)",
    },
    {
        "name": "trace-core",
        "path": "``packages/trace-core``",
        "feature": "Decision log: capture, sync, read and search agent sessions",
        "language": "TypeScript",
        "runtime": "Node (CLI and hooks), and inside the server",
        "build": "pnpm + tsdown",
        "ownership": "Whiteboard-owned (private)",
        "upstream": "—",
        "entrypoint": "``whiteboard trace …``; hooks call ``whiteboard trace git-hook …``",
        "inputs": "Harness session files and hook events; Git commits",
        "outputs": "Uploaded sessions; ``Agent-Session`` trailers; normalized JSONL",
        "consumers": "CLI, server (Trace tab, quote validation), FFF search",
        "persistence": "``$DEV_REVIEW_HOME/trace``, ``trace-search/``; Git notes ``refs/notes/dev-fast/*``",
        "network": "S3/R2 (via the ``aws`` CLI) or the hosted store ``https://app.dev.fast``",
        "credentials": "AWS/R2 credentials, or a hosted login (Bearer token)",
        "verification": "250 tests (run); real stores NOT verified",
        "origin": "Split out in #253–#256; consolidated into the CLI in #365",
        "confidence": "CONFIRMED",
    },
    {
        "name": "trace-protocol",
        "path": "``packages/trace-protocol``",
        "feature": "Contract with the hosted trace store",
        "language": "TypeScript (zod)",
        "runtime": "Node (CLI) and the external store server",
        "build": "tsc; published to npm (0.5.0)",
        "ownership": "Whiteboard-owned, published",
        "upstream": "—",
        "entrypoint": "``storeRoutes``, schemas",
        "inputs": "—",
        "outputs": "Schemas, limits, route builders and matchers",
        "consumers": "trace-core; the hosted store (external)",
        "persistence": "—",
        "network": "—",
        "credentials": "—",
        "verification": "17 tests (run)",
        "origin": "``trace-shared`` (``9ae532cd``), renamed in #256",
        "confidence": "CONFIRMED",
    },
    {
        "name": "local-vcs",
        "path": "``packages/local-vcs``",
        "feature": "Pins, diffs, blob reads and file locks over Git and Jujutsu",
        "language": "TypeScript",
        "runtime": "Node; shells out to ``git`` and ``jj``",
        "build": "tsdown; published (0.1.0)",
        "ownership": "Whiteboard-owned, published",
        "upstream": "—",
        "entrypoint": "``detectLocalVcs()``, ``git()``, ``resolveRevision()``",
        "inputs": "Repository paths and revisions",
        "outputs": "Resolved commits, diffs, file contents",
        "consumers": "review-api, trace-core, sharing",
        "persistence": "Git notes, lock files",
        "network": "``git fetch`` of PR refs (through review-api)",
        "credentials": "The user's Git credentials",
        "verification": "69 tests (run)",
        "origin": "Pre-import",
        "confidence": "CONFIRMED",
    },
    {
        "name": "json",
        "path": "``packages/json``",
        "feature": "JSON decoding at boundaries",
        "language": "TypeScript",
        "runtime": "Node / browser",
        "build": "tsc",
        "ownership": "Whiteboard-owned (private)",
        "upstream": "—",
        "entrypoint": "``jsonObject``, ``jsonString``, ``parseJsonText``",
        "inputs": "Untyped JSON",
        "outputs": "Typed values",
        "consumers": "Most packages",
        "persistence": "—",
        "network": "—",
        "credentials": "—",
        "verification": "Typecheck (run)",
        "origin": "Split from review-protocol in #256",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Claude / Codex / Cursor plugins",
        "path": "``packages/agent-plugins/{claude,codex,cursor}``, ``.claude-plugin/``, ``.agents/plugins/``",
        "feature": "Connect coding agents",
        "language": "JSON manifests",
        "runtime": "The agent host",
        "build": "None",
        "ownership": "Whiteboard-owned",
        "upstream": "Agent plugin formats (external)",
        "entrypoint": "``.mcp.json``: ``sh -c 'exec \"$HOME/.local/bin/whiteboard\" mcp'``",
        "inputs": "—",
        "outputs": "An MCP server registration",
        "consumers": "Claude Code, Codex, Cursor",
        "persistence": "—",
        "network": "—",
        "credentials": "—",
        "verification": "``agent-plugins.test.ts`` (run); real hosts NOT verified",
        "origin": "#475",
        "confidence": "CONFIRMED",
    },
    {
        "name": "OpenCode plugin",
        "path": "``packages/agent-plugins/opencode``",
        "feature": "Connect OpenCode",
        "language": "JavaScript",
        "runtime": "OpenCode's plugin runtime",
        "build": "None (published as-is, 0.1.1)",
        "ownership": "Whiteboard-owned",
        "upstream": "``@opencode-ai/plugin`` (types)",
        "entrypoint": "Default export ``whiteboardPlugin()`` → ``config`` hook",
        "inputs": "OpenCode config",
        "outputs": "``config.mcp.whiteboard`` (local command)",
        "consumers": "OpenCode",
        "persistence": "—",
        "network": "—",
        "credentials": "—",
        "verification": "Test coverage in ``agent-plugins.test.ts`` (run)",
        "origin": "#84, then #465, then #475",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Pi skill package",
        "path": "``packages/agent-plugins/pi``",
        "feature": "Connect Pi (skill, not MCP)",
        "language": "Markdown skill",
        "runtime": "Pi agent",
        "build": "None (published, 0.1.1)",
        "ownership": "Whiteboard-owned",
        "upstream": "Pi package conventions",
        "entrypoint": "``skills/whiteboard/SKILL.md``",
        "inputs": "—",
        "outputs": "Instructs Pi to run ``whiteboard api …``",
        "consumers": "Pi",
        "persistence": "—",
        "network": "—",
        "credentials": "—",
        "verification": "Test coverage (run)",
        "origin": "#475, #537",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Agent instructions",
        "path": "``packages/review/instructions/*.md``",
        "feature": "Server-served guidance (authoring, lenses, scratchpad, trace archaeology)",
        "language": "Markdown",
        "runtime": "Served by the server",
        "build": "Shipped in the npm package",
        "ownership": "Whiteboard-owned",
        "upstream": "—",
        "entrypoint": "``session_get_instructions({topic})``",
        "inputs": "Topic; capability context",
        "outputs": "Text",
        "consumers": "Agents",
        "persistence": "—",
        "network": "—",
        "credentials": "—",
        "verification": "``instructions.test.ts`` (run)",
        "origin": "The ``skills/dev-review`` skill pre-import; rewritten in #463",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Legacy importer",
        "path": "``packages/review/src/review-import/``, ``migrate.ts``",
        "feature": "Migrate MDX reviews to JSON",
        "language": "TypeScript",
        "runtime": "Node (startup, ``migrate apply``)",
        "build": "Bundled",
        "ownership": "Whiteboard-owned (legacy support)",
        "upstream": "—",
        "entrypoint": "Startup importer; ``whiteboard migrate apply``",
        "inputs": "``$DEV_REVIEW_HOME/reviews/<uuid>/``",
        "outputs": "JSON reviews",
        "consumers": "Server startup",
        "persistence": "Reads the legacy tree; writes the store",
        "network": "—",
        "credentials": "—",
        "verification": "Golden fixtures (run; needs Git ``safe.directory`` under root)",
        "origin": "#296; the MDX writer was removed in #312 and #322",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Telemetry",
        "path": "``review-telemetry.ts``, ``ui-telemetry-events.ts``, ``posthog-capture-client.ts``",
        "feature": "Anonymous usage and reliability data",
        "language": "TypeScript",
        "runtime": "Node (servers and CLI); events relayed from the renderer",
        "build": "Bundled; a key is embedded at release (``embed-posthog-key.mjs``)",
        "ownership": "Whiteboard-owned; the PostHog service is external",
        "upstream": "PostHog",
        "entrypoint": "``ReviewTelemetry.fromEnv()``",
        "inputs": "Events; opt-out environment variables",
        "outputs": "HTTPS to ``https://us.i.posthog.com``",
        "consumers": "Product team",
        "persistence": "Install ID; queued events",
        "network": "Yes",
        "credentials": "Embedded project key",
        "verification": "``test:telemetry-privacy`` tests (run); delivery NOT verified",
        "origin": "Pre-import; contract formalized in #533 and #550",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Curated extensions and language servers",
        "path": "``apps/review-desktop/scripts/curated-extensions*.mjs``",
        "feature": "LSP navigation (Rust, Swift, C#, Python …) and keymaps",
        "language": "Various (third-party VSIX)",
        "runtime": "Code - OSS extension host",
        "build": "Downloaded from ``https://open-vsx.org`` at build time",
        "ownership": "External",
        "upstream": "Open VSX publishers",
        "entrypoint": "``curated-extensions.mjs``",
        "inputs": "Manifest",
        "outputs": "Extensions under ``code-oss/extensions`` (gitignored)",
        "consumers": "Desktop",
        "persistence": "—",
        "network": "Yes (open-vsx.org)",
        "credentials": "—",
        "verification": "NOT verified (open-vsx.org blocked here)",
        "origin": "Pre-import",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Desktop build and packaging scripts",
        "path": "``apps/review-desktop/scripts/*.sh``, ``*.mjs``, ``*.py``",
        "feature": "Build, run, package (DMG, Squirrel zips, Fedora RPM repositories)",
        "language": "Bash, Node ESM, Python",
        "runtime": "Developer machine / CI runner",
        "build": "—",
        "ownership": "Whiteboard-owned",
        "upstream": "Wraps the Code - OSS build",
        "entrypoint": "``build.sh``, ``run.sh``, ``package-macos.sh``, ``package-linux*.sh``",
        "inputs": "The repository",
        "outputs": "``.build/electron``, packaged apps",
        "consumers": "``pnpm dev``, release workflows",
        "persistence": "Freshness stamps in ``code-oss/.build/dev-fast``",
        "network": "Yes",
        "credentials": "Apple signing (releases)",
        "verification": "Script unit tests (105 run); the build itself FAILED (network)",
        "origin": "Pre-import",
        "confidence": "CONFIRMED",
    },
    {
        "name": "CLI release and smoke scripts",
        "path": "``scripts/*.mjs``",
        "feature": "Pack, smoke-test and publish ``@dev.fast/review``",
        "language": "Node ESM",
        "runtime": "CI",
        "build": "—",
        "ownership": "Whiteboard-owned",
        "upstream": "—",
        "entrypoint": "``review-cli-release.mjs``, ``pack-review-cli.mjs``, ``smoke-review-cli.mjs``",
        "inputs": "Workspace",
        "outputs": "Tarball; npm publication",
        "consumers": "``review-cli-release.yml``",
        "persistence": "—",
        "network": "npm registry",
        "credentials": "npm provenance (OIDC)",
        "verification": "``node --test scripts/**/*.test.mjs`` 11/11 (run)",
        "origin": "#367",
        "confidence": "CONFIRMED",
    },
    {
        "name": "GitHub Actions workflows",
        "path": "``.github/workflows/*.yml``",
        "feature": "CI, desktop preview and release, CLI release, Linux packages",
        "language": "YAML",
        "runtime": "``ubuntu-latest``, ``review_big_boy``, ``macos-15-xlarge``",
        "build": "—",
        "ownership": "Whiteboard-owned",
        "upstream": "Pinned third-party actions (SHA-pinned, #19)",
        "entrypoint": "Push, PR and ``workflow_dispatch`` triggers",
        "inputs": "Repository",
        "outputs": "Checks, releases",
        "consumers": "Maintainers",
        "persistence": "—",
        "network": "Yes",
        "credentials": "Apple, npm and GitHub secrets",
        "verification": "NOT run in this fork (no check runs on PR #1)",
        "origin": "Pre-import",
        "confidence": "CONFIRMED",
    },
    {
        "name": "anti-slop lint plugin",
        "path": "``tools/oxlint/anti-slop``",
        "feature": "Code quality rules",
        "language": "TypeScript (oxlint JS plugin)",
        "runtime": "oxlint",
        "build": "Loaded from source by oxlint",
        "ownership": "Vendored (partially) + Whiteboard-owned rules",
        "upstream": "``dmmulroy/anti-slop``",
        "entrypoint": "``.oxlintrc.json`` ``jsPlugins``",
        "inputs": "Source",
        "outputs": "Diagnostics",
        "consumers": "``pnpm lint``",
        "persistence": "—",
        "network": "—",
        "credentials": "—",
        "verification": "``pnpm lint`` (run)",
        "origin": "#95",
        "confidence": "CONFIRMED",
    },
    {
        "name": "review-latency harness",
        "path": "``scripts/review-latency``",
        "feature": "Measure prompt-to-document latency for authoring runs",
        "language": "Python ≥3.12",
        "runtime": "CPython via ``uv``",
        "build": "hatchling (``pyproject.toml``), ``uv.lock``",
        "ownership": "Whiteboard-owned (developer tool)",
        "upstream": "—",
        "entrypoint": "``uv run review-latency``",
        "inputs": "``runs.toml``; an installed ``/Applications/Whiteboard.app``; ``claude``",
        "outputs": "Run directories, HTML dashboards",
        "consumers": "Developers",
        "persistence": "``~/.dev/review-latency/runs``",
        "network": "Agent API",
        "credentials": "Agent login",
        "verification": "``uv run review-latency --help`` (run); real runs need macOS",
        "origin": "#157",
        "confidence": "CONFIRMED",
    },
    {
        "name": "Sphinx documentation",
        "path": "``docs/``",
        "feature": "Developer documentation",
        "language": "reStructuredText + Python config",
        "runtime": "Python / Sphinx 9",
        "build": "``sphinx-build``",
        "ownership": "Whiteboard-owned",
        "upstream": "Sphinx, sphinxcontrib-mermaid",
        "entrypoint": "``docs/conf.py``",
        "inputs": "``.rst`` files",
        "outputs": "HTML",
        "consumers": "Developers",
        "persistence": "``docs/_build`` (gitignored)",
        "network": "Mermaid from a CDN at view time",
        "credentials": "—",
        "verification": "``sphinx-build -W`` + Mermaid render check (run)",
        "origin": "PR #1 in this fork",
        "confidence": "CONFIRMED",
    },
    {
        "name": "progressive-review remnant",
        "path": "``packages/progressive-review/tutorial/data.ts``",
        "feature": "None today (legacy tutorial data)",
        "language": "TypeScript",
        "runtime": "—",
        "build": "Not a workspace package (no ``package.json``)",
        "ownership": "Legacy",
        "upstream": "—",
        "entrypoint": "—",
        "inputs": "—",
        "outputs": "—",
        "consumers": "UNVERIFIED (no importer found by name)",
        "persistence": "—",
        "network": "—",
        "credentials": "—",
        "verification": "—",
        "origin": "The main package until #259 renamed ``progressive-review`` to ``review``",
        "confidence": "HISTORY",
    },
    {
        "name": "Upstream Rust in Code - OSS",
        "path": "``code-oss/cli/`` (VS Code CLI), ``code-oss/build/win32/`` (Inno updater)",
        "feature": "None in Whiteboard (not built or shipped)",
        "language": "Rust",
        "runtime": "—",
        "build": "Cargo (upstream), never invoked by Whiteboard scripts",
        "ownership": "Vendored upstream",
        "upstream": "``microsoft/vscode``",
        "entrypoint": "—",
        "inputs": "—",
        "outputs": "—",
        "consumers": "None found",
        "persistence": "—",
        "network": "—",
        "credentials": "—",
        "verification": "``git grep`` finds no build reference in scripts or workflows",
        "origin": "``d1c6463c`` import",
        "confidence": "INFERRED",
    },
]


def main() -> None:
    out: list[str] = []
    w = out.append
    w("Component registry")
    w("==================")
    w("")
    w(".. This page is generated by docs/tools/component_registry.py. Edit the")
    w("   data there and regenerate; do not edit this file by hand.")
    w("")
    w("A census of every subsystem we found by scanning manifests, file types,")
    w("build scripts and runtime entrypoints, not only the pnpm workspace list.")
    w("Scan summary (first-party means outside ``apps/review-desktop/code-oss``):")
    w("")
    w("* First-party: 599 ``.ts``, 133 ``.tsx``, 74 ``.mjs``, 20 ``.py``, 13 ``.sh``,")
    w("  and 2 ``.rs`` / 2 ``.go`` (LSP e2e fixtures only).")
    w("* Vendored Code - OSS: 6,406 files, including 4,940 ``.ts`` and 77 ``.rs``")
    w("  (upstream ``cli/`` and ``build/win32/``).")
    w("* **No first-party Rust, Cargo workspace or WASM build exists in this")
    w("  repository.** The Rust semantic-diff engine is the external ``diffr``")
    w("  binary. See :doc:`semantic_diff/index`.")
    w("")
    w("Summary")
    w("-------")
    w("")
    w(".. list-table::")
    w("   :header-rows: 1")
    w("   :widths: 26 18 22 18 16")
    w("")
    w("   * - Component")
    w("     - Language")
    w("     - Runtime")
    w("     - Ownership")
    w("     - Confidence")
    for c in REGISTRY:
        w(f"   * - :ref:`{c['name']} <reg-{slug(c['name'])}>`")
        w(f"     - {c['language']}")
        w(f"     - {c['runtime']}")
        w(f"     - {c['ownership']}")
        w(f"     - {c['confidence']}")
    w("")
    w("Entries")
    w("-------")
    for c in REGISTRY:
        missing = [k for k, _ in FIELDS if k not in c]
        if missing:
            raise SystemExit(f"{c['name']}: missing {missing}")
        w("")
        w(f".. _reg-{slug(c['name'])}:")
        w("")
        w(c["name"])
        w("~" * max(len(c["name"]), 4))
        w("")
        w(".. list-table::")
        w("   :widths: 22 78")
        w("")
        for key, label in FIELDS:
            w(f"   * - {label}")
            w(f"     - {c[key]}")
    target = Path(__file__).resolve().parents[1] / "src/architecture/component_registry.rst"
    target.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {target} ({len(REGISTRY)} components)")


def slug(name: str) -> str:
    return "".join(ch if ch.isalnum() else "-" for ch in name.lower().replace("``", "")).strip("-")


if __name__ == "__main__":
    main()
